In [28]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt

# Configuración
# -----------------------------------------------------------------------
# para poder visualizar todas las columnas de los DataFrames
pd.set_option('display.max_columns', None)

#### ---- INDICE ----  

[- Visualización Inicial](#visualizacion-inicial)  
[- Análisis Descriptivo](#analisis-descriptivo)  
[- Limpieza](#limpieza)  
    [------> Insertado columnas para el análisis](#insertamos-columna-de-niveles-de-rendimiento)  
[- Traducción de archivo](#traduccion)  
[- Guardado de archivo limpio](#guardado-de-archivo) 
 
#### ------------------

#### VISUALIZACION INICIAL

In [29]:
# Read the CSV file
# The CSV file is read using pd.read_csv() and stored in the DataFrame df.
df = pd.read_csv('StudentPerformanceFactors_INEE.csv')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [30]:
print(f'El DF tiene {df.shape[0]} filas y {df.shape[1]} columnas.')

El DF tiene 6607 filas y 20 columnas.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

#### ANALISIS DESCRIPTIVO

In [32]:
    # COLUMNAS CATEGÓRICAS --> valores únicos
# Devuelve tablas con las diferentes categorias de las columnas que encontramos en el dataframe
for col in df.select_dtypes(include='O').columns:
    print(f"Las categorías que tenemos para la columna {col} son:")
    display(df[col].value_counts().reset_index())
    print('_' * 100)

Las categorías que tenemos para la columna Parental_Involvement son:

  Parental_Involvement  count
0               Medium   3362
1                 High   1908
2                  Low   1337

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Access_to_Resources son:

  Access_to_Resources  count
0              Medium   3319
1                High   1975
2                 Low   1313

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Extracurricular_Activities son:

  Extracurricular_Activities  count
0                        Yes   3938
1                         No   2669

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Motivation_Level son:

  Motivation_Level  count
0           Medium   3351
1              Low   1937
2             High   1319

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Internet_Access son:

  Internet_Access  count
0             Yes   6108
1              No    499

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Family_Income son:

  Family_Income  count
0           Low   2672
1        Medium   2666
2          High   1269

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Teacher_Quality son:

  Teacher_Quality  count
0          Medium   3925
1            High   1947
2             Low    657

____________________________________________________________________________________________________
Las categorías que tenemos para la columna School_Type son:

  School_Type  count
0      Public   4598
1     Private   2009

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Peer_Influence son:

  Peer_Influence  count
0       Positive   2638
1        Neutral   2592
2       Negative   1377

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Learning_Disabilities son:

  Learning_Disabilities  count
0                    No   5912
1                   Yes    695

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Parental_Education_Level son:

  Parental_Education_Level  count
0              High School   3223
1                  College   1989
2             Postgraduate   1305

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Distance_from_Home son:

  Distance_from_Home  count
0               Near   3884
1           Moderate   1998
2                Far    658

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Gender son:

   Gender  count
0    Male   3814
1  Female   2793

____________________________________________________________________________________________________

In [33]:
    # COLUMNAS NUMÉRICAS
# Análisis descriptivo / estadístico
df.select_dtypes(exclude='O').describe().T

                    count       mean        std   min   25%   50%   75%    max
Hours_Studied      6607.0  19.975329   5.990594   1.0  16.0  20.0  24.0   44.0
Attendance         6607.0  79.977448  11.547475  60.0  70.0  80.0  90.0  100.0
Sleep_Hours        6607.0   7.029060   1.468120   4.0   6.0   7.0   8.0   10.0
Previous_Scores    6607.0  75.070531  14.399784  50.0  63.0  75.0  88.0  100.0
Tutoring_Sessions  6607.0   1.493719   1.230570   0.0   1.0   1.0   2.0    8.0
Physical_Activity  6607.0   2.967610   1.031231   0.0   2.0   3.0   4.0    6.0
Exam_Score         6607.0  67.235659   3.890456  55.0  65.0  67.0  69.0  101.0

### LIMPIEZA

In [34]:
# Comprobamos que no haya valores duplicados:
print(f'Valores duplicados: {df.duplicated().sum()}.')

Valores duplicados: 0.

In [35]:
# Tenemos valores nulos:
    # Sacamos el df con los valores nulos
df_nulos = df.isnull().sum().reset_index()
    # Cambiamos el nombre de las columnas
df_nulos.columns= ['Columnas', 'Valores_Nulos(%)']
    # Nos quedamos con las columnas que tengan valores distintos de 0
df_nulos = df_nulos[df_nulos['Valores_Nulos(%)'] != 0]
    # Añadimos una columna con los porcentajes resultantes
porcentaje_nulos = round(df_nulos['Valores_Nulos(%)']/df.shape[0]*100,2)
df_nulos['Porcentaje_Nulos'] = porcentaje_nulos
df_nulos

                    Columnas  Valores_Nulos(%)  Porcentaje_Nulos
11           Teacher_Quality                78              1.18
16  Parental_Education_Level                90              1.36
17        Distance_from_Home                67              1.01

In [36]:
# IMPUTACIÓN DE VALORES
# Son variables CATEGÓRICAS con menos del 5% de nulos:
# volvemos a ver los valores únicos:
columnas_cat_nulos = ['Teacher_Quality','Parental_Education_Level','Distance_from_Home']
for col in df[columnas_cat_nulos].columns:
    print(f"Las categorías que tenemos para la columna {col} son:")
    display(df[col].value_counts().reset_index())
    print('_' * 100)

Las categorías que tenemos para la columna Teacher_Quality son:

  Teacher_Quality  count
0          Medium   3925
1            High   1947
2             Low    657

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Parental_Education_Level son:

  Parental_Education_Level  count
0              High School   3223
1                  College   1989
2             Postgraduate   1305

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Distance_from_Home son:

  Distance_from_Home  count
0               Near   3884
1           Moderate   1998
2                Far    658

____________________________________________________________________________________________________

In [37]:
display(df[columnas_cat_nulos].describe().T)
print('Claramente se ve que la MODA en todas las categorías es clara.')

                         count unique          top  freq
Teacher_Quality           6529      3       Medium  3925
Parental_Education_Level  6517      3  High School  3223
Distance_from_Home        6540      3         Near  3884

Claramente se ve que la MODA en todas las categorías es clara.

In [38]:
# Rellenaremos los datos faltantes por la MODA de cada categoría
# iteramos por la lista creada en el paso anterior:
for columna in columnas_cat_nulos:
    # calculamos la moda
    moda = df[columna].mode()[0]    
    # método fillna para reemplazar los valores nulos por la moda
    df[columna] = df[columna].fillna(moda)

# chequeamos si se han eliminado los nulos
print("Después del reemplazo usando 'fillna' quedan los siguientes nulos")
df[columnas_cat_nulos].isnull().sum()

Después del reemplazo usando 'fillna' quedan los siguientes nulos

Teacher_Quality             0
Parental_Education_Level    0
Distance_from_Home          0
dtype: int64

### Insertamos columna de niveles de rendimiento:

5 NIVELES  
- Exam_Score

In [39]:
round(df['Exam_Score'].describe(),2)
# mínimo --> 55
# máximo --> 101

count    6607.00
mean       67.24
std         3.89
min        55.00
25%        65.00
50%        67.00
75%        69.00
max       101.00
Name: Exam_Score, dtype: float64

Nivel más bajo de rendimiento:
1) Nivel 1 --> bajo rendimiento  -------------------->  55 - 64  
Se establecen tres niveles intermedios:  
2) Nivel 2 --> intermedio bajo  -------------------->  65 -73 
3) Nivel 3 --> intermedio central  -------------------->  74 - 82  
4) Nivel 4 --> intermedio alto   -------------------->  83 - 91  
Finalmente, el nivel más alto:  
5) Nivel 5: alto rendimiento  -------------------->  92 - 101

In [40]:
# sacamos la columna 'Exam_Score'
exam_score = list(df['Exam_Score']) # array --> lista

# bucle vamos obteniendo los grupos de categorías
perf_levels= []

for v in exam_score:
    if 55 <= v <= 64:
        perf_levels.append(1)
    if 65 <= v <= 73:
        perf_levels.append(2)
    if 74 <= v <= 82:
        perf_levels.append(3)
    if 83 <= v <= 91:
        perf_levels.append(4)
    if 92 <= v <= 101:
        perf_levels.append(5)

# comprobamos
print(f'Total de elementos del df: {df.shape[0]}.')
print(f'Total de elementos de la lista: {len(perf_levels)}.')

Total de elementos del df: 6607.
Total de elementos de la lista: 6607.

In [41]:
# añadimos la columna al df:
df['Performance_Levels'] = perf_levels
df.head(2)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Performance_Levels
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67,2
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61,1

- Previus_Score

In [42]:
round(df['Previous_Scores'].describe(),2)
# mínimo --> 50
# máximo --> 100

count    6607.00
mean       75.07
std        14.40
min        50.00
25%        63.00
50%        75.00
75%        88.00
max       100.00
Name: Previous_Scores, dtype: float64

Nivel más bajo de rendimiento:
1) Nivel 1 --> bajo rendimiento  -------------------->  50 - 60  
Se establecen tres niveles intermedios:  
2) Nivel 2 --> intermedio bajo  -------------------->  61 -70 
3) Nivel 3 --> intermedio central  -------------------->  71 - 79  
4) Nivel 4 --> intermedio alto   -------------------->  80 - 89  
Finalmente, el nivel más alto:  
5) Nivel 5: alto rendimiento  -------------------->  90 - 100

In [43]:
# sacamos la columna 'Exam_Score'
prev_score = list(df['Previous_Scores']) # array --> lista

# bucle vamos obteniendo los grupos de categorías
perf_prev_levels= []

for v in prev_score:
    if 50 <= v <= 60:
        perf_prev_levels.append(1)
    if 61 <= v <= 70:
        perf_prev_levels.append(2)
    if 71 <= v <= 79:
        perf_prev_levels.append(3)
    if 80 <= v <= 89:
        perf_prev_levels.append(4)
    if 90 <= v <= 100:
        perf_prev_levels.append(5)

# comprobamos
print(f'Total de elementos del df: {df.shape[0]}.')
print(f'Total de elementos de la lista: {len(perf_prev_levels)}.')

Total de elementos del df: 6607.
Total de elementos de la lista: 6607.

In [44]:
# añadimos la columna al df:
df['Previous_Perf_Levels'] = perf_prev_levels
df.head(2)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Performance_Levels,Previous_Perf_Levels
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67,2,3
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61,1,1

In [45]:
# Valores únicos --> columnas rendimienro
columnas_cat_nulos = ['Previous_Perf_Levels','Performance_Levels']
for col in df[columnas_cat_nulos].columns:
    print(f"Las categorías que tenemos para la columna {col} son:")
    display(df[col].value_counts().reset_index())
    print('_' * 100)

Las categorías que tenemos para la columna Previous_Perf_Levels son:

   Previous_Perf_Levels  count
0                     5   1391
1                     1   1356
2                     2   1346
3                     4   1324
4                     3   1190

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Performance_Levels son:

   Performance_Levels  count
0                   2   4925
1                   1   1452
2                   3    191
3                   5     21
4                   4     18

____________________________________________________________________________________________________

#### TRADUCCION

In [46]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score', 'Performance_Levels', 'Previous_Perf_Levels'],
      dtype='object')

In [47]:
df.columns = ['Horas_Estudio', 'Asistencia', 'Involucración_Padres', 'Acceso_Recursos', 'Actividades_Extraescolares',
              'Horas_Sueño', 'Puntuación_Anterior', 'Nivel_Motivación', 'Acceso_Internet',
              'Tutorías', 'Ingreso_Familiar', 'Calidad_Profesorado', 'Tipo_Centro',
              'Influencia_Compañeros', 'Actividad_Física', 'Problemas_Aprendizaje',
              'Nivel_Educación_Padres', 'Distancia_Vivienda', 'Género', 'Puntuación', 'Niveles_Rendimiento', 'Niveles_Previos_Rto']

In [48]:
    # Valores:
# Bajo, Medio, Alto --> Involucración_Padres, Acceso_Recursos, Nivel_Motivación, Ingreso_Familiar, Calidad_Profesorado
# Sí, No --> Actividades_Extraescolares, Acceso_Internet, Problemas_Aprendizaje
# Público, Privado --> Tipo_Escuela
# Positiva, Neutral, Negativa
# Instituto, Universidad, Postgrado --> Nivel_Educación_Padres
# Cercana, Moderada, Lejana --> Distancia_Vivienda
# Hombre, Mujer --> Género

reemplazos = {
    'Low':'Bajo', 'Medium':'Medio', 'High':'Alto',
    'Yes': 'Sí', 'No': 'No',
    'Public':'Público', 'Private':'Privado',
    'Positive': 'Positiva', 'Neutral': 'Neutral', 'Negative': 'Negativa',
    'High School': 'Instituto', 'College' : 'Universidad', 'Postgraduate': 'Postgrado',
    'Near': 'Cercana', 'Moderate': 'Moderada', 'Far': 'Lejana',
    'Male': 'Hombre', 'Female': 'Mujer'    
}

df = df.replace(reemplazos)

In [49]:
for col in df.select_dtypes(include='O').columns:
    print(f"Las categorías que tenemos para la columna {col} son:")
    display(df[col].value_counts().reset_index())
    print('_' * 100)

Las categorías que tenemos para la columna Involucración_Padres son:

  Involucración_Padres  count
0                Medio   3362
1                 Alto   1908
2                 Bajo   1337

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Acceso_Recursos son:

  Acceso_Recursos  count
0           Medio   3319
1            Alto   1975
2            Bajo   1313

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Actividades_Extraescolares son:

  Actividades_Extraescolares  count
0                         Sí   3938
1                         No   2669

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Nivel_Motivación son:

  Nivel_Motivación  count
0            Medio   3351
1             Bajo   1937
2             Alto   1319

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Acceso_Internet son:

  Acceso_Internet  count
0              Sí   6108
1              No    499

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Ingreso_Familiar son:

  Ingreso_Familiar  count
0             Bajo   2672
1            Medio   2666
2             Alto   1269

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Calidad_Profesorado son:

  Calidad_Profesorado  count
0               Medio   4003
1                Alto   1947
2                Bajo    657

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Tipo_Centro son:

  Tipo_Centro  count
0     Público   4598
1     Privado   2009

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Influencia_Compañeros son:

  Influencia_Compañeros  count
0              Positiva   2638
1               Neutral   2592
2              Negativa   1377

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Problemas_Aprendizaje son:

  Problemas_Aprendizaje  count
0                    No   5912
1                    Sí    695

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Nivel_Educación_Padres son:

  Nivel_Educación_Padres  count
0              Instituto   3313
1            Universidad   1989
2              Postgrado   1305

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Distancia_Vivienda son:

  Distancia_Vivienda  count
0            Cercana   3951
1           Moderada   1998
2             Lejana    658

____________________________________________________________________________________________________
Las categorías que tenemos para la columna Género son:

   Género  count
0  Hombre   3814
1   Mujer   2793

____________________________________________________________________________________________________

### GUARDADO DE ARCHIVO

In [ ]:
# Guarda el DataFrame como un archivo CSV
# df.to_csv("SPF_INEE_clean_spanish.csv", index=False)

In [56]:
# Read the CSV file
# The CSV file is read using pd.read_csv() and stored in the DataFrame df.
df_clean_spanish = pd.read_csv('SPF_INEE_clean_spanish.csv')
df_clean_spanish.head(2)

,Horas_Estudio,Asistencia,Involucración_Padres,Acceso_Recursos,Actividades_Extraescolares,Horas_Sueño,Puntuación_Anterior,Nivel_Motivación,Acceso_Internet,Tutorías,Ingreso_Familiar,Calidad_Profesorado,Tipo_Centro,Influencia_Compañeros,Actividad_Física,Problemas_Aprendizaje,Nivel_Educación_Padres,Distancia_Vivienda,Género,Puntuación,Niveles_Rendimiento,Niveles_Previos_Rto
0,23,84,Bajo,Alto,No,7,73,Bajo,Sí,0,Bajo,Medio,Público,Positiva,3,No,Instituto,Cercana,Hombre,67,2,3
1,19,64,Bajo,Medio,No,8,59,Bajo,Sí,2,Medio,Medio,Público,Negativa,4,No,Universidad,Moderada,Mujer,61,1,1

In [57]:
df_clean_spanish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Horas_Estudio               6607 non-null   int64
 1   Asistencia                  6607 non-null   int64
 2   Involucración_Padres        6607 non-null   object
 3   Acceso_Recursos             6607 non-null   object
 4   Actividades_Extraescolares  6607 non-null   object
 5   Horas_Sueño                 6607 non-null   int64
 6   Puntuación_Anterior         6607 non-null   int64
 7   Nivel_Motivación            6607 non-null   object
 8   Acceso_Internet             6607 non-null   object
 9   Tutorías                    6607 non-null   int64
 10  Ingreso_Familiar            6607 non-null   object
 11  Calidad_Profesorado         6607 non-null   object
 12  Tipo_Centro                 6607 non-null   object
 13  Influencia_Compañeros       6607 non-null   object
 14  Actividad_Física            6607 non-null   int64
 15  Problemas_Aprendizaje       6607 non-null   object
 16  Nivel_Educación_Padres      6607 non-null   object
 17  Distancia_Vivienda          6607 non-null   object
 18  Género                      6607 non-null   object
 19  Puntuación                  6607 non-null   int64
 20  Niveles_Rendimiento         6607 non-null   int64
 21  Niveles_Previos_Rto         6607 non-null   int64
dtypes: int64(9), object(13)
memory usage: 1.1+ MB